### ISSUE TITLE
bootstrap.sh is not enough

### ISSUE THREAD

**Issue by atomicbird** [aaronpearce/SF-Viewer#1]
I ran `bootstrap.sh` as the README indicates and it seems to have worked as intended. If I look at `Symbals/Configuration/Local/DevTeam.xcconfig` it shows the correct `LOCAL_DEVELOPMENT_TEAM`, anyway.

However building for devices fails because Xcode still tries to use the wrong development team. It's necessary to change the team in Xcode too, because Xcode still wants to use the team found in the project file.

<img width="515" alt="Screen Shot 2020-01-02 at 3 31 58 PM" src="https://user-images.githubusercontent.com/15008/71697519-74124780-2d75-11ea-8587-e15d7b5aebd5.png">

Changing the team in Xcode fixes the issue and the app builds. This is with Xcode 11.2.1 (11B53).

**Comment by aaronpearce** [comment]
I've possibly misconfigured something as it should automatically switch, I'll dig into this when I get a chance and see.

**Comment by aaronpearce** [comment]
@atomicbird The latest push should have fixed this.

**Comment by atomicbird** [comment]
That changes the error but `bootstrap.sh` still isn't doing it for me. I did a fresh clone and then did this:

    % sh bootstrap.sh 
    Creating 'Local' directory
    Choose your developer team that you wish to sign SF Viewer with:
    1) iPhone Developer: Tom Harrington (VC7282VPMT)
    2) Apple Development: Tom Harrington (VC7282VPMT)
    3) Apple Development: Tom Harrington (ELDFJKP8FN)
    4) Quit
    #? 1
    You selected 'iPhone Developer: Tom Harrington (VC7282VPMT)' as your developer team, we've written this to 'Symbals/Configuration/Local/DevTeam.xcconfig'

So far so good. But Xcode's still not happy.

<img width="506" alt="Screen Shot 2020-01-02 at 3 58 11 PM" src="https://user-images.githubusercontent.com/15008/71698416-b0937280-2d78-11ea-87ad-f6fc1dee57c4.png">

Digging a little deeper, `VC7282VPMT` is what `bootstrap.sh` finds, but does not match what I see when I log in to my Apple developer account. It's not a different team, though, because I can replace the end of the URL with `VC7282VPMT` and the developer site shows me the same team. It's as if I have two different team IDs and Xcode only likes the one that `bootstrap.sh` can't find. If I try `security find-identity -v -p codesigning`, the results do not include the team ID shown at Apple's developer site.

This might be an unusual or unique situation. I don't know what to make of it.
